import numpy as np
x = np.array([1,2,3,4,5])
y = np.array([-1,-2,-3,-4,-5])
w = np.array((x,y))
print('minimum of x is {}'.format(np.min(x)))
print('minimum of x y is {}'.format(np.min(w)))
print('maximum of x is {}'.format(np.max(y)))
print('maximum of x y is {}'.format(np.max(w)))

product1 = np.prod(x)
product2 = np.prod(x)*np.prod(y)
print('product of x is {}'.format(product1))
print('product of x y is {}'.format(product2))
print('range of y is ({},{})'.format(np.min(y),np.max(y)))
print('range of x y is ({},{})'.format(np.min(w), np.max(w)))
print('sum of x is {}'.format(np.sum(x)))
print('sum of x y is {}'.format(np.sum(w)))
print('x*y is {}'.format(x*y))
print('y*x is {}'.format(y*x))
print('5*x is {}'.format(5*x))
print('y*5 is {}'.format(y*5))
x_new = np.delete(x,2)
y_new = np.delete(y,-1)

z = np.concatenate([x_new,y_new])
print('z array is {}'.format(z))